package com.sqwid.blockconstructor.blocks

import com.sqwid.blockconstructor.data.BlockInstance

/**
 * Lowers a script's block tree to a single Lua source string, ready to be fed to LuaEngine.
 *
 * The root block is expected to be the program block (specId = "program"). The generated
 * file always starts with a header comment so debugging output stays readable.
 */
object LuaCodegen {
    fun generate(root: BlockInstance, scriptName: String): String {
        val ctx = EmitContext()
        val spec = BlockCatalog.byId(root.specId)
            ?: return "-- root block missing spec '${root.specId}'"
        val body = spec.emit(root, ctx)
        return buildString {
            append("-- generated by Block Constructor\n")
            append("-- script: ").append(scriptName).append('\n')
            append("-- date: ").append(java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(java.util.Date()))
            append('\n').append('\n')
            append(body)
            append('\n')
        }
    }
}
